version: '3'
services:
  backend:
    build: ./backend
    ports:
      - '3001:3001'
    depends_on:
      - database
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
  database:
    image: mongo:4.4
    ports:
      - '27017:27017'
